# 30_Settings.yml
# 2014-12-13 00:21:33
# read from : /var/www/typo3-6.2/typo3conf/ext/theme_bootstrap_formhandler/Documentation/_make/../Settings.yml
# written to: /var/www/typo3-6.2/typo3conf/ext/theme_bootstrap_formhandler/Documentation/_make/_not_versioned/30_Settings.yml
# Could not find '/var/www/typo3-6.2/typo3conf/ext/theme_bootstrap_formhandler/Documentation/_make/../Settings.yml'.

--- null
...
